#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = d_cvport

# --------------------------------------------------------------
# Files to build

FILES_DSP = \
	ExamplePluginCVPort.cpp

# --------------------------------------------------------------
# Do some magic

include ../../Makefile.plugins.mk

# --------------------------------------------------------------
# Enable all possible plugin types

TARGETS = jack lv2_dsp

all: $(TARGETS)

# --------------------------------------------------------------
